PWEBAssignment/Models/Company.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace PWEBAssignment.Models
{
    public class Company
    {
        public int Id { get; set; }

        [Display(Name = "Name", Description = "Company's name", Prompt = "Insert the name of the Company")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 2)]
		public string Name { get; set; }

        [Display(Name = "Address", Description = "Company's address", Prompt = "Insert the address of the Company")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 2)]
		public string Address { get; set; }

        [Display(Name = "Rating", Description = "Company's Rating", Prompt = "Insert the rating of the Company")]
        [Range(0,5, ErrorMessage = "The Rating needs to be between 0 and 5")]
        public int Rating { get; set; }

        [Display(Name = "Available", Description = "Company's Availability")]
		public bool Available { get; set; }
        public ICollection<ApplicationUser> Workers { get; set; } //can be both Managers or Employee

        public ICollection<Car> Cars { get; set; } //all of the cars that the company runs
   
    }
}

PWEBAssignment/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.OutputCaching;
using Microsoft.EntityFrameworkCore;
using PWEBAssignment.Data;
using PWEBAssignment.Models;

namespace PWEBAssignment.Controllers
{
	[Authorize(Roles = "Admin,Employee,Manager")]
	public class CompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly INotyfService _toastNotification;
        public CompaniesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, INotyfService toastNotification)
        {
            _context = context;
            _userManager = userManager;
            _toastNotification = toastNotification;
        }

        // GET: Companies
        public async Task<IActionResult> Index()
        {
              return _context.Company != null ? 
                          View(await _context.Company.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Company'  is null.");
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Company == null)
            {
                return NotFound();
            }

            var company = await _context.Company
                .FirstOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,Rating,Available")] Company company)
        {
            ModelState.Remove(nameof(company.Available));
            ModelState.Remove(nameof(company.Rating));
            ModelState.Remove(nameof(company.Workers));
            ModelState.Remove(nameof(company.Cars));



            var equals = await _context.Company.FirstOrDefaultAsync(c =>
                c.Name.ToUpper().Equals(company.Name.ToUpper()));
            if (equals != null)
                ModelState.AddModelError("Name", "A Company with that name already exists");

            if (!ModelState.IsValid)
                return View(company);

            company.Available = false;
            company.Rating = 0;
            var defaultUser = new ApplicationUser
            {
                UserName = company.Name.Replace(" ", "") + "@gmail.com",
                Email = company.Name.Replace(" ", "") + "@gmail.com",
                firstName = "Manager",
                lastName = company.Name.Replace(" ", ""),
                EmailConfirmed = true,
                PhoneNumberConfirmed = true
            };
            var user = await _userManager.FindByEmailAsync(defaultUser.Email);

            if (user == null)
            {
                await _userManager.CreateAsync(defaultUser, "CompanyManager.0");
                await _userManager.AddToRoleAsync(defaultUser,
                    Roles.Manager.ToString());
                user = await _userManager.FindByEmailAsync(defaultUser.Email);
                company.Workers = new Collection<ApplicationUser>();
                company.Cars = new Collection<Car>();
                company.Workers.Add(user);
            }

            _context.Add(company);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public static string FormatString(string input)
		{
			input = input.ToLowerInvariant();

			string[] words = input.Split(' ');

			string firstLetter = words[0].Substring(0, 1).ToUpperInvariant();

			string output = string.Concat(firstLetter, words[0].Substring(1));

			for (int i = 1; i < words.Length; i++)
			{
				output = string.Concat(output, words[i]);
			}

			output = output.TrimEnd();

			output = string.Concat(output, ".0");

			return output;
		}
		



		// GET: Companies/Edit/5
		public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Company == null)
            {
                return NotFound();
            }

            var company = await _context.Company.FindAsync(id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,Rating,Available")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }

            ModelState.Remove(nameof(company.Rating));
            ModelState.Remove(nameof(company.Workers));
            ModelState.Remove(nameof(company.Cars));
            if (ModelState.IsValid)
            {


                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Company == null)
            {
                return NotFound();
            }

            var company = await _context.Company
                .FirstOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Company == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Company'  is null.");
            }

            var teste = await _context.Reservations.Where(r => r.CompanyId == id && r.ReturnId==null).FirstOrDefaultAsync();
            if (teste != null)
            {
                _toastNotification.Error("This company has reservations");
                return RedirectToAction(nameof(Index));
            }


            var users = await _userManager.Users.Where(u => u.CompanyID == id).ToListAsync();
            foreach (var u in users)
            {
                await _userManager.DeleteAsync(u);
            }

            var cars = await _context.Car.Where(u => u.CompanyID == id).ToListAsync();

            foreach (var c in cars)
            {
                _context.Car.Remove(c);

                await _context.SaveChangesAsync();
            }


            var company = await _context.Company.FindAsync(id);
            if (company != null)
            {
                

                _context.Company.Remove(company);
                await _context.SaveChangesAsync();
            }
            
          /*  await _context.SaveChangesAsync();*/
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyExists(int id)
        {
          return (_context.Company?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> ActivateCompany(int id)
        {
            var company = await _context.Company.Where(c => c.Id == id).FirstOrDefaultAsync();

            if (company == null)
                return RedirectToAction(nameof(Index));

            if (company.Available)
                company.Available = false;
            else
                company.Available = true;

            _context.Update(company);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

     
    }
}

PWEBAssignment/Views/Companies/Create.cshtml
@model PWEBAssignment.Models.Company

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Company</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" asp-items="ViewBag.Address">
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
	        <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PWEBAssignment/Views/Companies/Delete.cshtml
@model PWEBAssignment.Models.Company

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
    
    <form asp-action="Delete">
	    <input type="hidden" asp-for="Id" />
	    <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
    <a asp-action="Index">Back to List</a>
</div>

PWEBAssignment/Views/Companies/Details.cshtml
@model PWEBAssignment.Models.Company

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Company</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
	    <dd class = "col-sm-10">
		    @Html.DisplayFor(model => model.Rating)
	    </dd>
	    <dt class = "col-sm-2">
		    @Html.DisplayNameFor(model => model.Available)
	    </dt>
	    <dd class="col-sm-10">
            @if (Model.Available)
            {
	            <p>True</p>
            }
            else
            {
	            <p>False</p>
            }
	    </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PWEBAssignment/Views/Companies/Edit.cshtml
@model PWEBAssignment.Models.Company

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Company</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
	            <label asp-for="Address" class="control-label"></label>
	            <input asp-for="Address" class="form-control" />
	            <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PWEBAssignment/Views/Companies/Index.cshtml
@model IEnumerable<PWEBAssignment.Models.Company>

@{
    ViewData["Title"] = "Index";
}

<div class="d-flex flex-grow-1 w-100 justify-content-between">
<h1>Index</h1>

<p>
	<a class="btn btn-primary mt-2" asp-action="Create">
		<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
			<path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z"/>
		</svg>
		Create New
	</a>
</p>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Available)
            </th>
	        <th></th>
	        <th></th>
	        <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
	        
	        <td>
		        @if (item.Available)
		        {
			        <a class="btn btn-primary"
			           asp-controller="Companies"
			           asp-action="ActivateCompany"
			           asp-route-id="@item.Id">Deactivate</a>
                    <p class="text-success">It is Activated</p>
		        }
		        else
		        {
			        <a class="btn btn-primary"
			           asp-controller="Companies"
			           asp-action="ActivateCompany"
			           asp-route-id="@item.Id">Activate</a>
			        <p class="text-danger">It is Deactivated</p>
		        }
		        <td>
                    <a class="btn btn-primary w-90" asp-action="Edit" asp-route-id="@item.Id">Edit</a>

                </td>
		        <td>
			        <a class="btn btn-primary w-90" asp-action="Details" asp-route-id="@item.Id">Details</a> 
		        </td>
		        <td>
                    <a class="btn btn-danger w-90" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
	        </td>
        </tr>
}
    </tbody>
</table>