PWEBAssignment/Controllers/UserManagerController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PWEBAssignment.Data;
using PWEBAssignment.Models;
using PWEBAssignment.ViewModels;
using System.Data;

namespace PWEBAssignment.Controllers
{
	[Authorize(Roles = "Manager")]
	public class UserManagerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly INotyfService _toastNotification;
        public UserManagerController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, INotyfService toastNotification)
        {
            _context = context;
            _userManager = userManager;
            _toastNotification = toastNotification;
        }
        public async Task<IActionResult> Index()
        {
            var userSelf = await _userManager.GetUserAsync(User);
            var users = await _userManager.Users.Where(c=>c.CompanyID == userSelf.CompanyID).ToListAsync();
            var userRolesViewModel = new List<UserRolesViewModel>();

            foreach (var user in users)
            {
                var role = await _userManager.GetRolesAsync(user);
           
                if (!role.Contains("Admin") && !role.Contains("Client"))
                {
                    userRolesViewModel.Add(new UserRolesViewModel
                    {
                        UserId = user.Id,
                        FirstName = user.firstName,
                        LastName = user.lastName,
                        UserName = user.UserName,
                        available = user.available,
                        Roles = await _userManager.GetRolesAsync(user),
                        /* Avatar = user.Avatar*/
                    });
                }
            }

            return View(userRolesViewModel);
        }
        public IActionResult Create(string type)
        {

            ViewData["Type"] = type;
            return View();
        }


        public async Task<IActionResult> ActivateUser(string userId)
        {
            var userAsked = await _userManager.FindByIdAsync(userId);
            var userSelf = await _userManager.GetUserAsync(User);

            if (userAsked == null || userAsked.Id == userSelf.Id)
            {
                _toastNotification.Information("You cannot change the status of yourself", 3);
                return RedirectToAction(nameof(Index));
            }
                
            
            if (userAsked.available)
                userAsked.available = false;
            else
                userAsked.available = true;


            await _userManager.UpdateAsync(userAsked);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(string userId)
        {
	        var userAsked = await _userManager.FindByIdAsync(userId);
	        var userSelf = await _userManager.GetUserAsync(User);

	        if (userAsked == null || userAsked.Id == userSelf.Id)
	        {
		        _toastNotification.Information("You cannot delete yourself", 3);
		        return RedirectToAction(nameof(Index));

			}

			var teste = await _context.Reservations.Where(r => r.ClientUserId.ToString() == userId).FirstOrDefaultAsync();
	        if(teste!=null)
	        {
		        return RedirectToAction(nameof(Index));
			}
	        await _userManager.DeleteAsync(userAsked);

	        return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string type,[Bind("FirstName,LastName,Email,Password")] ManagerCreateUser newUser)
        {
	        if (ModelState.IsValid)
	        {
                var verify = await _userManager.FindByEmailAsync(newUser.Email);

                if (verify != null)
                {
                    _toastNotification.Information("An account with that email already exists in the database", 3);
                    return View(newUser);
				}
					


				var loggedUser = await _userManager.GetUserAsync(User);
		        var companyUser = await _context.Company.Where(c => c.Id == loggedUser.CompanyID).FirstOrDefaultAsync();
		        var defaultUser = new ApplicationUser
		        {
			        UserName = newUser.Email,
			        Email = newUser.Email,
			        firstName = newUser.FirstName,
			        lastName = newUser.LastName,
			        EmailConfirmed = true,
			        PhoneNumberConfirmed = true
		        };
		        var user = await _userManager.FindByEmailAsync(defaultUser.Email);
		        if (user == null)
		        {
			        await _userManager.CreateAsync(defaultUser, newUser.Password);

			        if (type.Equals("Manager"))
			        {
				        await _userManager.AddToRoleAsync(defaultUser,
					        Roles.Manager.ToString());
			        }
			        else
			        {
				        await _userManager.AddToRoleAsync(defaultUser,
					        Roles.Employee.ToString());
			        }


			        user = await _userManager.FindByEmailAsync(defaultUser.Email);
			        companyUser.Workers.Add(user);
			        await _context.SaveChangesAsync();
				}
		       
				return RedirectToAction(nameof(Index));
	        }
	        return View(newUser);
		}

    }
}

PWEBAssignment/Views/userManager/Create.cshtml
@using PWEBAssignment.Models
@model PWEBAssignment.ViewModels.ManagerCreateUser
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2> Creating a new @ViewData["Type"]</h2>

<div class="col-md-4">
	<form asp-action="Create" method="post">
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		<div class="form-group">
			<label asp-for="FirstName" class="control-label"></label>
			<input asp-for="FirstName" class="form-control" />
			<span asp-validation-for="FirstName" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="LastName" class="control-label"></label>
			<input asp-for="LastName" class="form-control" asp-items="ViewBag.Address">
			<span asp-validation-for="LastName" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Email" class="control-label"></label>
			<input asp-for="Email" class="form-control" asp-items="ViewBag.Address">
			<span asp-validation-for="Email" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Password" class="control-label"></label>
			<input asp-for="Password" class="form-control" asp-items="ViewBag.Address">
			<span asp-validation-for="Password" class="text-danger"></span>
		</div>
		<div class="form-group">
			<input type="submit" value="Create" class="btn btn-primary" asp-route-type="@ViewData["Type"]" />
		</div>
	</form>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PWEBAssignment/Views/userManager/Index.cshtml
@using PWEBAssignment.Models
@model List<PWEBAssignment.ViewModels.UserRolesViewModel>
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Company Accounts</h1>

<div class ="mb-4 mt-4">

	<a class="btn btn-primary"
	   asp-controller="UserManager"
	   asp-action="Create" asp-route-type="Manager">Create Manager</a>

	<a class="btn btn-primary"
	   asp-controller="UserManager"
	   asp-action="Create" asp-route-type="Employe">Create Employee</a>
</div>
<table class="table table-striped">
	<thead>
	<tr>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Email</th>
		<th>Roles</th>
		<th></th>
		<th></th>
	</tr>
	</thead>
	<tbody>
	@foreach (var userRoles in Model)
	{
		<tr >
			<td>

				@if (userRoles.Roles.Contains("Manager") || userRoles.Roles.Contains("Employee"))
				{
					<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-building" viewBox="0 0 16 16">
						<path d="M4 2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1ZM4 5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1ZM7.5 5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1Zm2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1ZM4.5 8a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1Zm2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1Z"/>
						<path d="M2 1a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V1Zm11 0H3v14h3v-2.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5V15h3V1Z"/>
					</svg>
				}
				@userRoles.FirstName
			</td>
			<td>@userRoles.LastName</td>
			<td>@userRoles.UserName</td>
			<td>@string.Join(", ", userRoles.Roles.ToList())</td>
			<td>
				<a class="btn btn-danger"
					asp-controller="UserManager"
				   asp-action="Delete"
				   asp-route-userId="@userRoles.UserId">Delete</a>
			</td>
			<td>
				@if (userRoles.available)
				{
					<a class="btn btn-primary"
					   asp-controller="UserManager"
					   asp-action="ActivateUser"
					   asp-route-userId="@userRoles.UserId">Deactivate</a>
				}
				else
				{
					<a class="btn btn-primary"
					   asp-controller="UserManager"
					   asp-action="ActivateUser"
					   asp-route-userId="@userRoles.UserId">Activate</a>
				}

			</td>
		</tr>
	}
	</tbody>
</table>